### PR TITLE
Ase module

### PR DESCRIPTION
**Pull request by nabeelp**
Fixed vnet and subnet naming
Fixed SKU reference for app service plan
Few description changes

### CODE REVIEW

**Comment by saumilmsft** [comment]
@nabeelp  - with ASEV3 are you able to deploy? in which region you're trying??
im seeing message saying its not avaiable in this region. I've tried East US, West US..

**Comment by saumilmsft** [comment]
if GA still not available we can change to ASEV2?

**Review by saumilmsft — APPROVED** [review]

**Comment by nabeelp** [comment]
> if GA still not available we can change to ASEV2?

I will see if we can parameterize this

**Comment by nabeelp** [comment]
> @nabeelp - with ASEV3 are you able to deploy? in which region you're trying??
> im seeing message saying its not avaiable in this region. I've tried East US, West US..

I have been using southafricanorth ... not sure what other regions support ASEv3

**Comment by nabeelp** [comment]
> > @nabeelp - with ASEV3 are you able to deploy? in which region you're trying??
> > im seeing message saying its not avaiable in this region. I've tried East US, West US..
> 
> I have been using southafricanorth ... not sure what other regions support ASEv3

It works for southcentralus as well

**Comment by saumilmsft** [comment]
> > if GA still not available we can change to ASEV2?
> 
> I will see if we can parameterize this

yes please.. its better we can make paraetrzed with default values incase if want we can override. also we need to mention location details to somewhere in readme file

**Pull request merged**
