### PR TITLE
Ahmeds/sharedrg

### PR DESCRIPTION
**Pull request by ahmedsza**
Shared resource group. Quite a few changes and refactoring. Tested on a clean sub (i.e all resource groups not available) and it works. Commented out ASE during testing

### CODE REVIEW

**Comment by torokzs** [comment]
It's not working for me. Using testpsscript.ps1 but commenting ase module out I get the following error for vnet-spoke-demoWL-dev-westeurope-001/vnet-spoke-demoWL-dev-westeurope-001-vnet-hub-demoWL-dev-westeurope:

{
    "status": "Failed",
    "error": {
        "code": "ReferencedResourceNotProvisioned",
        "message": "Cannot proceed with operation because resource /subscriptions/9e58876d-671b-4ef1-b43f-ddb3a4c1ecd9/resourceGroups/rg-networking-demoWL-dev-westeurope-001/providers/Microsoft.Network/virtualNetworks/vnet-hub-demoWL-dev-westeurope used by resource /subscriptions/9e58876d-671b-4ef1-b43f-ddb3a4c1ecd9/resourceGroups/rg-networking-demoWL-dev-westeurope-001/providers/Microsoft.Network/virtualNetworks/vnet-spoke-demoWL-dev-westeurope-001/virtualNetworkPeerings/vnet-spoke-demoWL-dev-westeurope-001-vnet-hub-demoWL-dev-westeurope is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is PutSubnetOperation.",
        "details": []
    }
}

**Comment by ahmedsza** [comment]
@cenkms  - can you have a look at this please. Seems like an issue on the networking module.

**Comment by ahmedsza** [comment]
@torokzs  - can you see if you had the RGs previously. I also hit some issues with the deployment when I already had some resource groups in place. After I deleted all RGs then it worked.

**Comment by torokzs** [comment]
> @torokzs - can you see if you had the RGs previously. I also hit some issues with the deployment when I already had some resource groups in place. After I deleted all RGs then it worked.

nly happens with brand new deployment. Second time there is a problem with the keyvault since its name exists somewhere else.

**Review by nabeelp — APPROVED** [review]
Tested with ASE commented out and all looks good. Made a few cosmetic changes, including the renaming of log anaytics and application insights

**Pull request merged**
